version: '3.9'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  orchestrator:
    build:
      context: .
      dockerfile: services/orchestrator/Dockerfile
    environment:
      - PORT=7070
      - REDIS_URL=redis://redis:6379
    ports:
      - "7070:7070"
    depends_on:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:7070/ready >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  redis-data: