apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator
  namespace: mentatlab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orchestrator-scheduler
  namespace: mentatlab
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestrator-scheduler-binding
  namespace: mentatlab
subjects:
  - kind: ServiceAccount
    name: orchestrator
    namespace: mentatlab
roleRef:
  kind: Role
  name: orchestrator-scheduler
  apiGroup: rbac.authorization.k8s.io

