name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Or appropriate Python version for your services

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or appropriate Node.js version for your frontend

      - name: Lint, Test, and Build Orchestrator
        run: |
          cd services/orchestrator
          pip install -r requirements.txt # Assuming requirements.txt exists
          pip install flake8 pytest
          flake8 .
          pytest
          docker build -t ghcr.io/flexinfer/mentatlab/orchestrator .

      - name: Lint, Test, and Build Gateway
        run: |
          cd services/gateway
          pip install -r requirements.txt # Assuming requirements.txt exists
          pip install flake8 pytest
          flake8 .
          pytest
          docker build -t ghcr.io/flexinfer/mentatlab/gateway .

      - name: Lint, Test, and Build EchoAgent
        run: |
          cd services/agents/echo
          pip install -r requirements.txt # Assuming requirements.txt exists
          pip install flake8 pytest
          flake8 .
          pytest
          docker build -t ghcr.io/flexinfer/mentatlab/echoagent .

      - name: Lint, Test, and Build Frontend
        run: |
          cd services/frontend
          npm install
          npm run lint
          npm test
          npm run build
          docker build -t ghcr.io/flexinfer/mentatlab/frontend .
