name: MentatLab Full Pipeline
on: [push, pull_request]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or appropriate Node.js version for your frontend

      - name: Install frontend dependencies
        run: npm --prefix services/frontend install

      - name: Run frontend unit tests
        run: npm --prefix services/frontend run test

      - name: Run E2E tests
        run: |
          echo "Starting backend services in background for E2E tests..."
          python services/orchestrator/app/main.py &
          python services/gateway/app/main.py &
          sleep 10 # Give services time to start
          npm --prefix services/frontend run e2e

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Or appropriate Python version for your services

      - name: Install backend dependencies
        run: |
          pip install -r services/orchestrator/requirements.txt
          pip install -r cli/mentatctl/requirements.txt
          pip install -r services/gateway/requirements.txt
          pip install -r services/agents/echo/requirements.txt

      - name: Run backend unit tests
        run: |
          pytest services/orchestrator/app/tests/
          pytest services/gateway/tests/
          pytest services/agents/echo/app/

  deploy-staging:
    needs: [test-frontend, test-backend]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging
        run: echo "Staging deployment placeholder"
