name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install PDM
        run: python3 -m pip install pdm
      - name: Install backend deps
        run: |
          pdm install -p services/gateway --no-editable --group :all
      - name: Install frontend deps
        run: npm --prefix services/frontend ci
      - name: Run backend tests
        run: pdm run -p services/gateway pytest -q
      - name: Start server
        run: |
          uvicorn services.gateway.app.main:app --port 8000 &
          echo $! > server.pid
          sleep 2
      - name: Curl healthz
        run: curl -f http://localhost:8000/healthz
      - name: Curl flow
        run: curl -f http://localhost:8000/flows/hello_chat
      - name: Stop server
        run: kill $(cat server.pid)
